export const ROUTES_PATH = {
  LOGIN: "/login",
  SIGNUP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  TERM_OF_SERVICE: "/term-of-service",
  CLASSROOMS: "/classrooms",
  QUESTIONS: "/questions",
  ACTIVITIES: "/activities",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  DOCUMENTS: "/documents",
  CALENDAR: "/calendar",
  IMPORT: "/import",
};
export const ROLE_TYPE = {
  TEACHER: "TEACHER",
  STUDENT: "STUDENT",
};
export const QUESTION_TYPES = {
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  TRUE_FALSE: "TRUE_FALSE",
  MULTIPLE_CORRECT: "MULTIPLE_CORRECT",
  FILL_IN: "FILL_IN",
};

export const ACTIVITY_TYPE = {
  HANGMAN: "HANGMAN",
  FLASH_CARD: "FLASH_CARD",
  MATRIX_WORD: "MATRIX_WORD",
};
export const MAP_ACTIVITY_NAME = {
  HANGMAN: "Hangman",
  FLASH_CARD: "Thẻ Flashcard",
  MATRIX_WORD: "Crossword",
};

export const MAP_LEVEL_LABEL = {
  EASY: "Dễ",
  MEDIUM: "Trung bình",
  HARD: "Khó",
};

export const ERROR_MESSAGE = {
  USERNAME_IS_REQUIRED: "USERNAME_IS_REQUIRED",
  USERNAME_EXISTED: "USERNAME_EXISTED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  VERIFY_LINK_HAS_EXPRIED: "VERIFY_LINK_HAS_EXPRIED",
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  NOT_FOUND: "NOT_FOUND",
  EXISTED: "EXISTED",
  WRONG_PASSWORD_TO_JOIN: "WRONG_PASSWORD_TO_JOIN",
  ALREADY_JOINED_THIS_CLASSROOM: "ALREADY_JOINED_THIS_CLASSROOM",
};
